### ISSUE TITLE
Aftermath settings in your RNG lua

### ISSUE THREAD

**Issue by Gotenn** [AlanWarren/gearswap#1]
I'm not nearly as LUA savvy as you are.  I was attempting to add your Aftermath settings and specific Weapon name sets into your RNG lua, the same way your DRK lua has. I cannot get it to work.

I get the error attempt to index field 'Gandiva' (a nil value)

the set is sets.midcast.RA.Gandiva.AM   (I already added your AM settings for classes.CustomMeleeGroups)

> `function update_melee_groups()
>     classes.CustomMeleeGroups:clear()
> 
>     -- mythic AM    
>     if (player.equipment.ranged == 'Armageddon' and (buffactive['Aftermath: Lv.1'] or buffactive['Aftermath: Lv.2'] or buffactive['Aftermath: Lv.3']))
> 			or (player.equipment.ranged == 'Gandiva' and (buffactive['Aftermath: Lv.1'] or buffactive['Aftermath: Lv.2'] or buffactive['Aftermath: Lv.3']))
> 			or (player.equipment.ranged == "Annihilator" and buffactive['Aftermath'])
> 			or (player.equipment.ranged == "Yoichinoyumi" and buffactive['Aftermath']) then
> 		classes.CustomMeleeGroups:append('AM')
>     end
> end`

The other issue I had was trying to add secondary WS sets for specific weapons. Specifically Trueflight with Gastraphedes: 

> `sets.Trueflight = set_combine(sets.Wildfire, {ear2="Moonshade Earring", left_ring="Weather. Ring",})
>         sets.precast.WS['Trueflight'] = set_combine(sets.precast.WS, sets.Trueflight)
>         sets.precast.WS['Trueflight'].Mid = set_combine(sets.precast.WS.Mid, sets.Trueflight)
>         sets.precast.WS['Trueflight'].Acc = set_combine(sets.precast.WS.Acc, sets.Trueflight)`
> 

> `sets.Trueflight.Gastraphetes = set_combine(sets.Wildfire, {ear2="Moonshade Earring", left_ring="Weather. Ring", {ammo="Quelling Bolt"}})
>         sets.precast.WS['Trueflight'].Gastraphetes = set_combine(sets.Trueflight.Gastraphetes)
>         sets.precast.WS['Trueflight'].Gastraphetes.Mid = set_combine(sets.Trueflight.Gastraphetes)
>         sets.precast.WS['Trueflight'].Gastraphetes.Acc = set_combine(sets.Trueflight.Gastraphetes)`

[RNG.zip](https://github.com/AlanWarren/gearswap/files/2594112/RNG.zip)

also I'm terrible at formatting

**Comment by AlanWarren** [comment]
I've added AM support to my RNG.lua fb76461b56cc589547c5c99bc620ffb53a733e37
I haven't added sets for these groups yet, but they'll behave similar to my DRK's.  sets.midcast.RA.Mid.AM3 for example.  

Mote's libs use CustomRangedGroups instead of CustomMeleeGroups for RA sets, so that could have been your issue.  

I also added support for named weapon sets.  This is a little tricky for weaponskills, as you have to use a custom function when using Mote's libs.  Otherwise, for regular ranged set support, I created get_combat_weapon. This too, should also function like my DRK's.   a55200bef3a0d479093f5a3d30d8364c87ff06db

I'm at work, and can't test this out.  Please let me know.

**Comment by Gotenn** [comment]
`        sets.midcast.RA.Gandiva.AM = { 
            head="Meghanada Visor +2",
			body="Mummu Jacket +2",
			hands="Mummu Wrists +2",
			legs="Mummu Kecks +2",
			feet="Mummu Gamash. +2",
			neck="Iskur Gorget",
			waist="K. Kachina Belt +1",
			left_ear="Telos Earring",
			right_ear="Enervating Earring",
			left_ring="Ilabrat Ring",
			right_ring="Begrudging Ring",
			back={ name="Belenus's Cape", augments={'DEX+20','Rng.Acc.+20 Rng.Atk.+20','Crit.hit rate+10','Damage taken-5%',}}
        }
        sets.midcast.RA.Gandiva.Mid.AM = set_combine(sets.midcast.RA.Gandiva.AM, {
        })
        sets.midcast.RA.Gandiva.Acc.AM = set_combine(sets.midcast.RA.Gandiva.Mid.AM, {
        })`

This is my sets for AM, but I still get the attemp to index field 'Gandiva' (a nil value)

also I was getting spammed by errer in the fuction buff_chage attempt to call global "determine_custom_ranged_groups" (a nil value)
and my gastra set for preshot was working, but no longer works.

**Comment by AlanWarren** [comment]
I just tested out my changes, and I accidentally put **player.equipment.main** instead of **player.equipment.range** for the weapon checks. 

I tested with Yoichinoyumi, and everything is working without any errors.  (tested sets based on weapon name, and WS sets using weapon name)

Just be careful merging in my changes. There's quite a lot of changes scattered all over the files. Click on the checksum for the git commits that I linked above, and look at the green areas.  There's a new commit here with the latest fix.  https://github.com/AlanWarren/gearswap/commit/a3568786516a73872606e3c2610414d512edd073

**Comment by Gotenn** [comment]
The index field 'Gandiva' is where I still get an error (a nil value), do I need to put Gandiva at the end?
`sets.midcast.RA.Gandiva.AM =`
`sets.midcast.RA.DoubleShot.Gandiva.AM =`

It seems to be the AM thats throwing it off, If I do
`sets.midcast.RA.Gandiva =`
It works fine, but adding the AM and it freaks out.

I also have your new get_custom_ranged_groups function but I get an error for job_buff_change with AM up, with AM down, no error.
` determine_custom_ranged_groups()`

**Comment by Gotenn** [comment]
Ok so I separated the flurry buff gain and gave AM in buff change its own If and I no longer get the `determine_custom_ranged_groups( )` error

	`if (player.equipment.ranged == 'Armageddon' and (buffactive['Aftermath: Lv.1'] or buffactive['Aftermath: Lv.2'] or buffactive['Aftermath: Lv.3']))
			or (player.equipment.ranged == 'Gandiva' and (buffactive['Aftermath: Lv.1'] or buffactive['Aftermath: Lv.2'] or buffactive['Aftermath: Lv.3']))
			or (player.equipment.ranged == "Annihilator" and buffactive['Aftermath'])
			or (player.equipment.ranged == "Yoichinoyumi" and buffactive['Aftermath']) then
		        determine_custom_ranged_groups()
		if not midaction() then
			handle_equipping_gear(player.status)
		end
	end`

again bad at formating, I dont know how to tab in this text box

edit: also wanted to let you know custom weapon WS do work, tested that out. I do really appreciate all the help your giving for weapons you don't have.

**Comment by AlanWarren** [comment]
Hey it’s np. I’ll look into this and let you know. 

See the notes I’ve put at the top of rng.lua for set order.

Make sure you are calling the ranged groups function everywhere that I am. It should be in three places iirc. 

I forgot Mote’s library also gives us CustomClass, which is another arbitrary set convention we can use. I could move flurry there if it helps. I’ll have to test

**Comment by Gotenn** [comment]
Another note I found, since i separated flurry from AM settings in the buff_change, I reverted your flurry back to the old way you had because you had removed the F1/F2 settings.

**Comment by AlanWarren** [comment]
Sorry for the delay. I think I found what was causing these issues. I had renamed the function responsible for setting up CustomRangedGroups, but didn't update it in job_buff_change().  

I tested with Annihilator, and sets.midcast.RA.Annihilator  and sets.midcast.RA.Annihilator.AM work as expected for me.  I didn't have to make any changes to F1 or F2.  

Just be aware, the "AM" set only works for relic aftermath.  Empy + Mythic will use AM1, AM2, and AM3.

**Comment by Gotenn** [comment]
OK I got everything working, I had to add a MILLION sets

https://drive.google.com/file/d/1KPgvqVU3J7_4sgHN-yLMxu72ZSR5EGu5/view?usp=sharing

basically I apparently wasn't building into the set, by creating the sub tables, so I needed a .RA.Gandiva set, before I made a .RA.Gandiva.AM1 set

**Comment by Gotenn** [comment]
Thank you so much for all your help!
