### ISSUE TITLE
Blu.lua

### ISSUE THREAD

**Issue by hedron2003** [AlanWarren/gearswap#3]
im trying to use your blu.lua and whenever i attack anything im getting unable to update combat form. 
![xiloader_BANwenDJg2](https://user-images.githubusercontent.com/56340511/66463515-34281680-ea4b-11e9-83a2-f22457d2c240.png)

idk how to attach a copy of the blu.lua its your with just my gear added tho i think
[blu.txt](https://github.com/AlanWarren/gearswap/files/3706236/blu.txt)

**Comment by AlanWarren** [comment]
Looks like your lua is cut off.  At the very bottom of the file you should have an empty update_combat_form() function, followed by the select_default_macro_book() function.

Add these lines to your file, and get rid of the send_command for changing macro books at the bottom.  You should use the function for that.  
https://github.com/AlanWarren/gearswap/blob/master/BLU.lua#L1089-L1108

**Comment by hedron2003** [comment]
looks like i forgot to reply to this thank you for the follow up btw
