### ISSUE TITLE
AM in the COR lua

### ISSUE THREAD

**Issue by Gotenn** [AlanWarren/gearswap#5]
I hate to ask again, but I tried to translate what we did to the RNG lua into the COR lua,  I just made Arma and setting AM up in the RNG lua was as easy as Copy/Paste my Gandiva sets and renaming them.  But trying to add the AM sets into the Cor Lua, it doesnt register that I have the AM buff up and keeps me in my normal shooting set.

**Comment by Gotenn** [comment]
Fixed it, I added the get_combat_weapon() function, but didnt add it to the top.

**Comment by AlanWarren** [comment]
glad you worked it out.
